# Generated by Django 2.1.15 on 2020-06-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='past_jon',
            new_name='past_job',
        ),
    ]
